
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  
  - name: last_buyed
    description: "Last buyed items for each customer"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  
  - name: ref_example
    description: "ref function example"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
